global:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  tolerations:
    - key: "apps"
      operator: "Equal"
      value: "nginx"
      effect: "NoSchedule"
server:
  service:
    type: NodePort
    nodePortHttp: 30081
    nodePortHttps: 30444
controller:
  extraArgs:
    - --app-resync=60         # how often (in seconds) to re-scan all Applications
    - --app-resync-jitter=10
