global:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  tolerations:
    - key: "apps"
      operator: "Equal"
      value: "nginx"
      effect: "NoSchedule"
server:
  service:
    type: NodePort
    nodePortHttp: 30081
    nodePortHttps: 30444
