apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
  namespace: apps
  labels:
    app: nginx-example
    version: v1.0.0
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    matchLabels:
      app: nginx-example
      version: v1.0.0
  template:
    metadata:
      labels:
        app: nginx-example
        version: v1.0.0
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m02
      tolerations:
        - key: "apps"
          operator: "Equal"
          value: "nginx"
          effect: "NoSchedule"
      containers:
        - name: nginx-example
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              memory: "256Mi"
