apiVersion: v1
kind: Service
metadata:
  name: nginx-example-service
  namespace: apps
spec:
  selector:
    app: nginx-example
    version: v1.0.0
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
